### ISSUE TITLE
Failed to execute script 'workaim' due to unhandled exception!

### ISSUE THREAD

**Issue by fastvariable** [Seconb/Arsenal-Colorbot#13]
Traceback (most recent call last):
  File "workaim.py", line 196, in <module>
RuntimeError: Failed to beep
[13184] Failed to execute script 'workaim' due to unhandled exception!
![image](https://github.com/Seconb/Arsenal-Colorbot/assets/130872826/c6e703a9-d209-4f15-a3af-ed69bf97774c)

**Comment by fastvariable** [comment]
hold works

**Comment by Seconb** [comment]
this bug is weird and i have no idea why it happens, the fix is to literally just remove the beeps from the source code (the .py)
