### ISSUE TITLE
Everytime I die the mouse moves up

### ISSUE THREAD

**Issue by arandomguythatspt** [Seconb/Arsenal-Colorbot#15]
Everytime I die the mouse moves up messing with the fullscreen
![image](https://github.com/Seconb/Arsenal-Colorbot/assets/154910461/71a2ca02-2a4f-4dc9-b5f3-7d46994a9c5a)
it does this annoying thing

**Comment by Seconb** [comment]
think i had that a couple times, nothing u can do. maybe the uwp doesnt have it id try that. ive also been told theres problems on the uwp so no guarantee it works
